"""Risk engine constants and thresholds."""

MIN_CONFIDENCE_BUY = 7.5
MIN_CONFIDENCE_HIGH_RISK = 9.0
MIN_THESIS_LENGTH = 20
APPROVED_FOR_PAPER = "APPROVED_FOR_PAPER"
APPROVED_FOR_MANUAL_REVIEW = "APPROVED_FOR_MANUAL_REVIEW"
REJECTED = "REJECTED"
NEEDS_MORE_DATA = "NEEDS_MORE_DATA"
